# Generated by Django 3.1.3 on 2020-11-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil_app', '0003_auto_20201107_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
